logbook.format.style=json
logbook.strategy=body-only-if-status-at-least
logbook.minimum-status=200

logbook.obfuscate.headers[0]=Authorization
logbook.obfuscate.parameters[0]=access_token
logbook.obfuscate.parameters[1]=password

logbook.predicate.include[0].path=/api/**
